services:
  frontend:
    container_name: erp_frontend
    build:
      context: ./frontend
      dockerfile: ../frontend.dockerfile
    volumes:
      - ./frontend/src:/home/node/app/src
      - ./frontend/public:/home/node/app/public
      - ./frontend/package.json:/home/node/app/package.json
      - ./frontend/package-lock.json:/home/node/app/package-lock.json
      - ./frontend/tsconfig.json:/home/node/app/tsconfig.json
      - ./frontend/tailwind.config.js:/home/node/app/tailwind.config.js
      - ./frontend/postcss.config.js:/home/node/app/postcss.config.js
      - ./frontend/components.json:/home/node/app/components.json
      - ./frontend/next.config.mjs:/home/node/app/next.config.mjs
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    ports:
      - "80:3000"
