services:
  frontend:
    container_name: erp_frontend
    build:
      context: .
      dockerfile: frontend.dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public
      - ./next.config.mjs:/home/node/app/next.config.mjs
      - ./package.json:/home/node/app/package.json
      - ./package-lock.json:/home/node/app/package-lock.json
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./tailwind.config.js:/home/node/app/tailwind.config.js
      - ./components.json:/home/node/app/components.json
      - ./postcss.config.js:/home/node/app/postcss.config.js
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "npm install && npm run dev"
    ports:
      - "80:3000"